### ISSUE TITLE
Add support for increasing number of partitions in a topic 

### ISSUE THREAD

**Issue by jurschel** [devshawn/kafka-gitops#34]
Given the following statefile:
```
#Orders
topics:
  orders:
    partitions: 5
    replication: 3
```
Desired state:
When I update partitions to 6 I expect the tool to increase the number of partitions.
Actual State:
Executing apply...
[SUCCESS] There are no necessary changes; the actual state matches the desired state.

Kafka Version -  2.1.1-cp1
Kafka-gitops version - 0.2.7

**Comment by devshawn** [comment]
That's correct, changing the number of partitions or changing the replication factor is not yet supported.

I should probably make that clearer in the docs.

**Comment by jurschel** [comment]
So what changes are supported?

**Comment by devshawn** [comment]
Changes to the number of partitions in a topic is a rare occurrence in my experience, and usually, something you want to have planned out (e.g. if you have keyed messages, you're now going to be distributing keys differently across the partitions). 

For topics, you can currently change its configs. For example:

```yaml
topics:
  test-topic:
    partitions: 6
    replication: 3
    configs:
      retention.ms: 60000
```

Changing a config:


```yaml
topics:
  test-topic:
    partitions: 6
    replication: 3
    configs:
      retention.ms: 30000
```

Most of the supported changes are for services/ACLs. However, I agree that this should be supported, and I'm working on adding this. 😄
