### ISSUE TITLE
Missing customUserAcls

### ISSUE THREAD

**Issue by infogulch** [devshawn/kafka-gitops#38]
I'm defining permissions for schema registry, but after applying none of the permissions listed under customerUserAcls are present in the cluster with a `kafka-acls.sh --list`

This is the customUserAcls section of my `state.yml` file:

```
customUserAcls:
  everyone:
    read-heartbeat:
      name: heartbeat
      principal: User:*
      type: TOPIC
      pattern: LITERAL
      host: "*"
      operation: READ
      permission: ALLOW

    describe-heartbeat:
      name: heartbeat
      principal: User:*
      type: TOPIC
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE
      permission: ALLOW

  # https://docs.confluent.io/current/schema-registry/security/index.html#authorizing-access-to-the-schemas-topic
  schema-registry:
    describe-cluster:
      name: kafka-cluster
      principal: User:schema-registry
      type: CLUSTER
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE
      permission: ALLOW
    
    create-cluster:
      name: kafka-cluster
      principal: User:schema-registry
      type: CLUSTER
      pattern: LITERAL
      host: "*"
      operation: CREATE
      permission: ALLOW
    
    describe-schemas:
      name: _schemas
      principal: User:schema-registry
      type: TOPIC
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE
      permission: ALLOW
      
    describeconfigs-schemas:
      name: _schemas
      principal: User:schema-registry
      type: TOPIC
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE_CONFIGS
      permission: ALLOW

    describe-consumer-offsets:
      name: __consumer_offsets
      principal: User:schema-registry
      type: TOPIC
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE
      permission: ALLOW
```

Any idea what's going on?

**Comment by devshawn** [comment]
Hey,

Does the plan have any changes when you try to plan? My guess is you're missing a definition of the user:

```
users:
  schema-registry:
    principal: User:schema-registry
    roles: []
```

It won't generate any ACLs for a user that isn't defined. I should probably make validation fail in that case.
