### ISSUE TITLE
Support for templating?

### ISSUE THREAD

**Issue by erikhh** [devshawn/kafka-gitops#46]
We run a multi tenant system. In general environments are the same except for the name of the tenant. To keep hosting overhead down we'd like to have all our tenants share one Kafka cluster. Where we keep the tenants apart using ACLs.

To do this now with Kafka-Gitops we would need to have a lot of repetition in our state file, and thus a lot of messy copy- paste-adapting every time we need to connect a new tentnat to our system. Or when we want to introduce a new application service for all our tenants.

In Terraform you can have variables and such, and generate resources for each item in a list. We've set it up so that we can just add the Tenant to a list and from there on Terraform creates all the resources needed for that tenant.
Are there any plans to add this kind of templating to Kafka-Gitops as well?

Maybe even just a way to share a custom ACL between multiple services or users without having to repeat the whole ACL for each and every service. That would already make the state file a whole lot more concise for us.

**Comment by devshawn** [comment]
Hi @erikhh, apologies for the late response. It's a busy time of year for me. :) 

I think this is a great idea, and we've discussed some similar features in some of the other open feature requests. I think some sort of templating would be helpful. Do you have specific examples of the types of templating that would benefit you the most?

> Maybe even just a way to share a custom ACL between multiple services or users without having to repeat the whole ACL for each and every one. That would already make the state file a whole lot more concise for us.

I like this idea -- agreed. I'll have to think about what the format of this would look like, but I think this is something that could be added in the near future.

**Comment by erikhh** [comment]
Hi @devshawn, I know right?! Same here, sorry for the late response.

For now I just had to get 'my thing' here going. So I went ahead and added a bit of [Mustashe](https://mustache.github.io/) to at least get my principal based repetition out of the way. It ain't exactly pretty but it's functional. I made our CI pipeline take a Mustasche template of the state.yaml and apply the correct variables for the environment it's building for to produce a full fledged state.yaml file that's published to a S3 bucket to be picked up.

Based on my experience with kafka-gitops so far it would already be really good (for me anyway) to DRY up the way you can add and assign custom service acls. There's a lot of repetition in using those. For example this is one of my entries now.

```
  {{.}}_journal-extractor:
    create-tenant-journal:
      name: journal-{{.}}
      type: TOPIC
      pattern: LITERAL
      host: '*'
      principal: User:{{.}}_journal-extractor
      operation: CREATE
      permission: ALLOW
    describe-tenant-journal:
      name: journal-{{.}}
      type: TOPIC
      pattern: LITERAL
      host: '*'
      principal: User:{{.}}_journal-extractor
      operation: DESCRIBE
      permission: ALLOW
    write-tenant-journal:
      name: journal-{{.}}
      type: TOPIC
      pattern: LITERAL
      host: '*'
      principal: User:{{.}}_journal-extractor
      operation: WRITE
      permission: ALLOW
    create-ship-journal:
      name: journal-{{.}}-ship-incoming-
      type: TOPIC
      pattern: PREFIXED
      host: '*'
      principal: User:{{.}}_journal-extractor
      operation: CREATE
      permission: ALLOW
    describe-ship-journal:
      name: journal-{{.}}-ship-incoming-
      type: TOPIC
      pattern: PREFIXED
      host: '*'
      principal: User:{{.}}_journal-extractor
      operation: DESCRIBE
      permission: ALLOW
    write-ship-journal:
      name: journal-{{.}}-ship-incoming-
      type: TOPIC
      pattern: PREFIXED
      host: '*'
      principal: User:{{.}}_journal-extractor
      operation: WRITE
      permission: ALLOW
``` 
First of all for some reason I had to repeat the principal over and over again, even tough it's also specified with the service already. But this might also be, just a bug.

It would already save a lot of repetition if you could pass more than one operation, maybe by accepting a list there in stead of a single value.

That could already reduce the above to something like:
```
{{.}}_journal-extractor:
  tenant-journal:
    name: journal-{{.}}
    type: TOPIC
    pattern: LITERAL
    host: '*'
    principal: User:{{.}}_journal-extractor
    operation: CREATE, DESCRIBE, WRITE
    permission: ALLOW
  ship-journal:
    name: journal-{{.}}-ship-incoming-
    type: TOPIC
    pattern: PREFIXED
    host: '*'
    principal: User:{{.}}_journal-extractor
    operation: CREATE, DESCRIBE, WRITE
    permission: ALLOW
```

And something similar would also clean up the custom user acls by pretty much the same amount.
