### ISSUE TITLE
Nullpointer exception thrown on empty topic properties.

### ISSUE THREAD

**Issue by RobinGoussey** [devshawn/kafka-gitops#47]
Hi, I tried running the docker (through docker compose), and I received a nullpointer exception without explenation. I don't really know if it can be seen as a bug, or missing error message. Basically if I just fill in the name of the topic, and rely on defaults, it gives a nullpointer exception.

I tried to create topics, but with all settings in default, and I got a nullpointer exception.
Command:
```shell output
$ docker-compose -f kafka-gitops.yml up
Recreating kafka-gitops ... done
Attaching to kafka-gitops
kafka-gitops    | 14:32:51.731 [main] INFO com.devshawn.kafka.gitops.config.KafkaGitopsConfigLoader - Kafka Config: {bootstrap.servers=localhost:9092, client.id=kafka-gitops}
kafka-gitops    | 14:32:51.735 [main] INFO com.devshawn.kafka.gitops.service.ParserService - Parsing desired state file...
kafka-gitops    | java.lang.NullPointerException
kafka-gitops    |       at com.devshawn.kafka.gitops.service.ParserService.parseStateFile(ParserService.java:84)
kafka-gitops    |       at com.devshawn.kafka.gitops.service.ParserService.parseStateFile(ParserService.java:42)
kafka-gitops    |       at com.devshawn.kafka.gitops.StateManager.getAndValidateStateFile(StateManager.java:72)
kafka-gitops    |       at com.devshawn.kafka.gitops.cli.ValidateCommand.call(ValidateCommand.java:26)
kafka-gitops    |       at com.devshawn.kafka.gitops.cli.ValidateCommand.call(ValidateCommand.java:15)
kafka-gitops    |       at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
kafka-gitops    |       at picocli.CommandLine.access$900(CommandLine.java:145)
kafka-gitops    |       at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
kafka-gitops    |       at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
kafka-gitops    |       at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
kafka-gitops    |       at picocli.CommandLine.execute(CommandLine.java:1904)
kafka-gitops    |       at com.devshawn.kafka.gitops.MainCommand.main(MainCommand.java:69)
kafka-gitops exited with code 1
```
docker-compose:
```yaml
version: '3'

services:
  kafka-gitops:
    image: devshawn/kafka-gitops
    container_name: kafka-gitops
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
    entrypoint: kafka-gitops -v -f /state-test.yml validate
    volumes:
    - ./state-test.yml:/state-test.yml
```
my desired state:
```yaml
topics:
  test:

settings:
  topics:
    defaults:
      partitions: 1
      replication: 1
      configs:
        cleanup.policy: delete
        retention.ms: -1
    blacklist:
      prefixed:
        - _confluent
```
