### ISSUE TITLE
Unable to import/match existing confluent cloud configuration in yaml

### ISSUE THREAD

**Issue by mundey** [devshawn/kafka-gitops#59]
environment: confluent cloud
I was trying to create state yaml so that it would not delete existing configuration:
-state.yaml-
```yaml
settings:
  ccloud:
    enabled: true
  topics:
    defaults:
      replication: 1
  files:
    topics: topics.yaml
    services: services.yaml

customServiceAcls:
  app-test:
    r-t-thg:
      name: temp.test.hello-kafka
      type: TOPIC
      pattern: LITERAL
      host: "*"
      operation: READ
      permission: ALLOW

```
-topics.yaml-
```yaml
topics:
  temp.test.hello-kafka:
    partitions: 3

```
-services.yaml-
```yaml
services:
  app-test:
    type: application

```
After clearing validation, when executed plan, it always shows removing existing acl/permission. I assumed service-account should exist in "services:" and under "customServiceAcls:" defining it's value as the service-account name as shown above. it's still not picking up. I tried to define principal for acl entry to match the User:{id} of "app-test" but the result is same.

Please help me with an example of import.
