### ISSUE TITLE
is it possible to specify multiple operations related to a single resource for acts

### ISSUE THREAD

**Issue by mundey** [devshawn/kafka-gitops#61]
when needed to specify entries for a service account but operations on same topic/group/resource, there is repetition. could it be possible to add operations in a single entry:
```yaml
customServiceAcls:
  dev_mgmt-test:
    d-cg-thg:
      name: test.hello-group
      type: GROUP
      pattern: LITERAL
      host: "*"
      operation: DESCRIBE,DESCRIBE_CONFIG,READ
      permission: ALLOW
```
