### ISSUE TITLE
Feature request: Possibility to manage ACLs only

### ISSUE THREAD

**Issue by TylerLubeck** [devshawn/kafka-gitops#79]
This is a lot like #51 , but for a different segment of configuration management.

I'm in a situation where it would be nice to only manage ACLs and not topics. We have a handful of tools that generate topics as needed (ksqldb, flink, some in-house applications), and we're in the middle of setting up ACLs for some of our other topics.

Problem is, any time we leave these configurations out of our state file, kafka-gitops tries to delete our topics. 

I saw that #54 got merged in, and I wrote #80 that basically copies that for `--skip-topics`. I'm wondering if I should instead investigate the possibility of automatically skipping plan segments if their keys are left out of the state file.

For instance, the following will delete all topics
```yaml
topics: []
services:
  example-service:
      type: application
      produces:
        - example-topic
```

But this one will leave any existing topics alone:
```yaml
services:
  example-service:
      type: application
      produces:
        - example-topic
```

**Comment by TylerLubeck** [comment]
Nevermind, I just found
```yaml
settings:
  topics:
    blacklist:
      prefixed:
        - ''
  ```
  
  Got way too excited to write some java and missed some documentation.
