### ISSUE TITLE
Allow specifying custom group IDs for services

### ISSUE THREAD

**Issue by devshawn** [devshawn/kafka-gitops#9]
Currently, `group.id`s are set based on the service name. We'd like to allow developers to set custom group IDs if needed.

**Comment by rkling01** [comment]
Great suggestion!  Would that option include enabling group * permissions - something like
 ```--allow-principal User:principal --operation read --topic test --group='*'```
or different thoughts on how would that type of acl be implemented?

**Comment by devshawn** [comment]
It could, though, I'm not sure it would be a good practice to allow a `*` for the custom group id of a specific service. This can, however, be done via the `customAclDetails` block. Documentation can be [found here](https://kafka-gitops.netlify.app/#/specification?id=custom-service-acls).

An example:

```yaml
customServiceAcls:
  my-service:
    read-topic-test:
      name: test
      type: TOPIC
      pattern: LITERAL
      host: "*"
      principal: User:principal
      operation: READ
      permission: ALLOW
    allow-all-groups:
      name: "*"
      type: GROUP
      pattern: LITERAL
      host: "*"
      principal: User:principal
      operation: READ
      permission: ALLOW
```

I think that would be correct. Hope that helps!

**Comment by mj550** [comment]
Kafka-Gitops is very easy to understand and apply.
Thanks for the example.
I have created a test topic and tried to add acl as provided in above example
`topics:
  test:
    partitions: 6
    replication: 3
    configs:
      cleanup.policy: compact

customServiceAcls:
  my-service:
    read-topic-test:
      name: test
      type: TOPIC
      pattern: LITERAL
      host: "*"
      principal: User:testcert
      operation: READ
      permission: ALLOW
    allow-all-groups:
      name: "*"
      type: GROUP
      pattern: LITERAL
      host: "*"
      principal: User:testcert
      operation: READ
      permission: ALLOW`


It created a topic 'test' and when I tried to list the ACL's assigned to 'test' topic. It didn't show any ACL's assigned to test also any ACL to Group with '*'.
Any suggestions?
AND
**Using kafka GitOps can we delete existing topics and ACL's ? Can you please provide example.**

**Comment by devshawn** [comment]
Hi @mj550, the ACLs are not being shown in the plan/apply because they are not tied to a service. You have to define `my-service` before the custom ACLs will be applied. 

Adding this block will make it work:

```yaml
services:
  my-service:
    type: application
    principal: User:testcert
```

As for your other questions, I've written up a demo with your YAML file as well as explained how deletion works. You can see the demo at this gist:

https://gist.github.com/devshawn/69969ff48434524e06bfbf596e40598b

I hope that helps! 😄
