### ISSUE TITLE
Connecting to service accounts created in CC

### ISSUE THREAD

**Issue by aditya-valstro** [devshawn/kafka-gitops#99]
Hello, I am trying to create custom ACL's for service accounts created through Terraform in Confluent Cloud. I am currently using 
```
customServiceAcls:
  development-SA-name:
    read-only-event-feed:
      name: event.feed
      type: TOPIC
      pattern: PREFIXED
      host: "*"
      principal: User:development-event-feed
      operation: READ
      permission: ALLOW
```

which references the service account already created in CC. When I run plan and apply it does not pickup any changes to ACLs:
`ACLs: 0 to create, 0 to update, 0 to delete.`

How can I create ACLs on Kafka topics defined in `state.yaml` for service accounts already existing in CC? Thanks!
